
service: media_alpha

provider:
  name: aws
  runtime: python3.6
  profile: MyZebraUser

functions:
  get_phone_number:
    handler: handler.get_phone_number
    events:
      - http:
          path: ''
          method: POST

plugins:
  - serverless-offline-python