service: media-alpha

provider:
  name: aws
  runtime: python3.6
  profile: MyZebraUser-staging
  region: us-west-1

functions:
  phone_number:
    handler: handler.get_phone_number
    events:
      - http:
          path: ''
          method: POST

plugins:
  - serverless-offline-python
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
