service: media-alpha

provider:
  name: aws
  runtime: python3.6
  profile: ${opt:aws-profile, 'MyZebraUser-staging'}
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    API_TOKEN: ${self:custom.stages.${self:provider.stage}.API_TOKEN}
    PLACEMENT_ID: ${self:custom.stages.${self:provider.stage}.PLACEMENT_ID}

functions:
  phone_number:
    handler: handler.get_phone_number
    events:
      - http:
          path: 'phone-number'
          method: POST
          cors: true

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-domain-manager

package:
  individually: true
  exclude:
    - .virtualenv/**
    - .venv/**
    - node_modules/**
    - venv/**

custom:
  pythonRequirements:
    dockerizePip: non-linux
    pythonBin: /opt/python3.6/bin/python
  customDomain:
    domainName: 'api.onebox.thezebra.com'
    basePath: 'mediaalpha-ivr'
    stage: ${self:provider.stage}
    createRoute53Record: true
  stages:
    dev:
      API_TOKEN: 'tKB5iqtmDYhs8oiypEhpHM'
      PLACEMENT_ID: 'd3kf4O0g8BTUCMfvPbFBQMGwbN0LqA'
      SLS_DEBUG: '*'
    prod:
      API_TOKEN: 'tKB5iqtmDYhs8oiypEhpHM'
      PLACEMENT_ID: 'd3kf4O0g8BTUCMfvPbFBQMGwbN0LqA'
