service: media-alpha

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    API_TOKEN: ${self:custom.stages.${self:provider.stage}.API_TOKEN}
    PLACEMENT_ID: ${self:custom.stages.${self:provider.stage}.PLACEMENT_ID}
    MEDIA_ALPHA_URL: ${self:custom.stages.${self:provider.stage}.MEDIA_ALPHA_URL}
    CI_REPO_NAME: ${git:repository}
    CI_COMMIT_ID: ${git:commit}
    CI_BRANCH: ${git:branch}

functions:
  phone_number:
    handler: handler.get_phone_number
    events:
      - http:
          path: 'phone-number'
          method: POST
          cors: true
  versioning:
    handler: healthcheck.check_version
    events:
      - http:
          path: 'version'
          method: GET
          cors: true

plugins:
  - serverless-offline
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-plugin-git-variables

package:
  individually: true
  exclude:
    - .virtualenv/**
    - node_modules/**

custom:
  pythonRequirements:
    dockerizePip: non-linux
  customDomain:
    domainName: 'api.onebox.thezebra.com'
    basePath: 'mediaalpha-ivr'
    stage: ${self:provider.stage}
    createRoute53Record: true
  stages:
    dev:
      API_TOKEN: 'tKB5iqtmDYhs8oiypEhpHM'
      PLACEMENT_ID: 'd3kf4O0g8BTUCMfvPbFBQMGwbN0LqA'
      MEDIA_ALPHA_URL: 'https://insurance-test.mediaalpha.com/ivr.json'
      SLS_DEBUG: '*'
    prod:
      API_TOKEN: 'tKB5iqtmDYhs8oiypEhpHM'
      PLACEMENT_ID: 'd3kf4O0g8BTUCMfvPbFBQMGwbN0LqA'
      MEDIA_ALPHA_URL: 'https://insurance-test.mediaalpha.com/ivr.json'
  exportGitVariables: false
